{% set name = "theme-darcula" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9a93d2bd76808e44e301f41b2ebb2446ca9b135fdc66c4f38978914ccf97313

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8
    - jupyterlab >=3.0.0,<4
    - nodejs
    - python >=3.6
    - pip
    - setuptools >=40.8.0
  run:
    - jupyterlab >=3.0.0,<4
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/telamonian/theme-darcula
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A handsome Darcula theme for Jupyterlab.

extra:
  recipe-maintainers:
    - rvalieris
    - dhirschfeld