{% set name = "theme-darcula" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/telamonian/theme-darcula/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 821551d5777ca8aee807b3ae481679a0545c87df42637d5c949792396364666e

build:
  noarch: python
  number: 1
  script: |
    set -euxo pipefail
    tree -a ./
    {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - jupyter-packaging >=0.12.3,<1
    - jupyterlab >=3.0.0,<5
    - nodejs
    - python >=3.6
    - pip
    - setuptools >=40.8.0
    - tree
  run:
    - jupyterlab >=3.0.0,<5
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/telamonian/theme-darcula
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A handsome Darcula theme for Jupyterlab.

extra:
  recipe-maintainers:
    - rvalieris
    - dhirschfeld
